@hostname = http://127.0.0.1:5002/api/v1/admission-test
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidG9rZW4iOiJxNm85anE4ZiIsInVzZXJfYWdlbnQiOiJ2c2NvZGUtcmVzdGNsaWVudCIsImlhdCI6MTcxNTQ5MzE0NH0.XAq9b9sahDzxrjSeuF1OS5WPFTjbhg_28ozJpx6odC4

# all
###
GET {{hostname}}?orderByCol=id&orderByAsc=true&show_active_data=true&paginate=10 HTTP/1.1

# get
###
GET {{hostname}}/1 HTTP/1.1

# store
###
POST  {{hostname}}/store HTTP/1.1
content-type: application/json

{
      "title": "admission test 2025",
      "description": "This is admission test account",
      "date": "25-01-2025",
      "class": "six",
      "admission_exam_date": "25-01-2025",
      "admission_result_date": "31-01-2025",
      "pass_mark": 75
}


# title: body.title,
#         description: body.description,
#         class: body.class,
#         admission_result_date: body.admission_result_date,
#         admission_exam_date: body.admission_exam_date,
#         pass_mark: body.pass_mark,



# update
###
POST {{hostname}}/update HTTP/1.1 
content-type: application/json

{
   "title": "admission test 2025",
      "description": "This is admission test account",
      "date": "25-01-2025",
      "class": "six",
      "admission_exam_date": "25-01-2025",
      "admission_result_date": "25-01-2025",
      "pass_mark": 75
}

# delete
###
POST  {{hostname}}/soft-delete HTTP/1.1
content-type: application/json

{
    "id": 1
}

# restore
###
POST  {{hostname}}/restore HTTP/1.1
content-type: application/json

{
    "id": 1
}


# destroy
###
POST  {{hostname}}/destroy HTTP/1.1
content-type: application/json

{
    "id": 4
}