@hostname = http://127.0.0.1:5002/api/v1/admission-candidate-test-submission
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidG9rZW4iOiJxNm85anE4ZiIsInVzZXJfYWdlbnQiOiJ2c2NvZGUtcmVzdGNsaWVudCIsImlhdCI6MTcxNTQ5MzE0NH0.XAq9b9sahDzxrjSeuF1OS5WPFTjbhg_28ozJpx6odC4

# all
###
GET {{hostname}}?orderByCol=id&orderByAsc=true&show_active_data=true&paginate=10 HTTP/1.1

# get
###
GET {{hostname}}/1 HTTP/1.1

# store
###
POST  {{hostname}}/store HTTP/1.1
content-type: application/json

{
   "id": 1,
   "question_id": 2,
   "question_title": "what is the capital city of bangladesh",
    "question_type": "quiz",
    "options1": "Dhaka",
    "options2": "Chittagoan",
    "options3": "rajshahi",
    "options4": "rangpur",
    "is_right_option_1": 0,
    "is_right_option_2": 1,
    "is_right_option_3": 0,
    "is_right_option_4": 0,
    "user_answer": 2,
    "marks": "3",
    "is_pass": 1,
    "right_answer": "",
    "given_addmission_date": "2025-01-15 07:03:51",
    "comment": ""


}

# {
#    "id": 1,
#    "question_id": 1,
#    "question_type": "written",
#     "question_title": "what is the capital city of bangladesh",
#     "right_answer": "bangladesh",
#     "user_answer":"BANGLADESH",
#     "marks": "3.25",
#     "is_pass": 1,
#     "given_addmission_date": "2025-01-15 07:03:51",
#     "comment": ""

# }






# update
###
POST {{hostname}}/update HTTP/1.1 
content-type: application/json

{
    "id": 4,
    "branch_id": "4",
    "title": "sellfin",
    "description": "This is sellfin account"
}

# delete
###
POST  {{hostname}}/soft-delete HTTP/1.1
content-type: application/json

{
    # "id": 4
}

# restore
###
POST  {{hostname}}/restore HTTP/1.1
content-type: application/json

{
    "id": 4
}


# destroy
###
POST  {{hostname}}/destroy HTTP/1.1
content-type: application/json

{
    "id": 4
}