@hostname = http://127.0.0.1:5002/api/v1/admission-test-questions
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidG9rZW4iOiJxNm85anE4ZiIsInVzZXJfYWdlbnQiOiJ2c2NvZGUtcmVzdGNsaWVudCIsImlhdCI6MTcxNTQ5MzE0NH0.XAq9b9sahDzxrjSeuF1OS5WPFTjbhg_28ozJpx6odC4

# all
###
GET {{hostname}} HTTP/1.1

# get 
###
GET {{hostname}}/1 HTTP/1.1

# store
###
POST  {{hostname}}/store HTTP/1.1
content-type: application/json

# {
#     "id": 1,
#     "admission_test_id": 1,
#     "branch_id": 1,
#     "class": "4",
#     "question_title": "what is the capital city of bangladesh? class 4",
#     "question_type": "quiz",
#     "options1": "Dhaka",
#     "options2": "CTG",
#     "options3": "Rangpur",
#     "options4": "Sylhet",
#     "is_right_option_1": 1,
#     "is_right_option_2": 0 ,
#     "is_right_option_3": 0,
#     "is_right_option_4": 0,
#     "right_answer": "1"
# }

{
    "id": 1,
    "admission_test_id": 1,
    "branch_id": 1,
    "class": "4",
    "question_title": "what is the our national fruits class 4",
    "question_type": "quiz",
    "options1": "Mango",
    "options2": "apple",
    "options3": "banana",
    "options4": "Jackfruit",
    "is_right_option_1": 0,
    "is_right_option_2": 0 ,
    "is_right_option_3": 0,
    "is_right_option_4": 1,
    "right_answer": "4",
    "mark": 3
}


# update
###
POST {{hostname}}/update HTTP/1.1 
content-type: application/json

{
     "id": 5,
    "question_title": "what is the port city of bangladesh",
    "question_type": "quiz",
    "options1": "Dhaka",
    "options2": "Chittagoan",
    "options3": "rajshahi",
    "options4": "rangpur",
    "is_right_option_1": 0,
    "is_right_option_2": 1,
    "is_right_option_3": 0,
    "is_right_option_4": 0
}

# delete
###
POST  {{hostname}}/soft-delete HTTP/1.1
content-type: application/json

{
    "id": 5
}

# restore
###
POST  {{hostname}}/restore HTTP/1.1
content-type: application/json

{
    "id": 5
}


# destroy
###
POST  {{hostname}}/destroy HTTP/1.1
content-type: application/json

{
    "id": 4
}