@hostname = http://127.0.0.1:5002/api/v1/admission-candidate
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidG9rZW4iOiJxNm85anE4ZiIsInVzZXJfYWdlbnQiOiJ2c2NvZGUtcmVzdGNsaWVudCIsImlhdCI6MTcxNTQ5MzE0NH0.XAq9b9sahDzxrjSeuF1OS5WPFTjbhg_28ozJpx6odC4

# all
###
GET {{hostname}}?orderByCol=id&orderByAsc=true&show_active_data=true&paginate=10 HTTP/1.1

# get
###
GET {{hostname}}/1 HTTP/1.1

# store
###
POST  {{hostname}}/store HTTP/1.1
content-type: application/json

{
    "id": 1,
    "user_id": 1,
    "exam_id": 1,
    "registration_date": "2025-01-15 06:27:41"
}


# update
###
POST {{hostname}}/update HTTP/1.1 
content-type: application/json

{
    "id": 1,
    "user_id": 1,
    "exam_id": 2,
    "registration_date": "2025-01-14 06:27:41"
}

# delete
###
POST  {{hostname}}/soft-delete HTTP/1.1
content-type: application/json

{
    # "id": 1
}

# restore
###
POST  {{hostname}}/restore HTTP/1.1
content-type: application/json

{
    # "id": 1
}


# destroy
###
POST  {{hostname}}/destroy HTTP/1.1
content-type: application/json

{
    # "id": 4
}